name: build

on:
  - push
  - pull_request

jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Test
        run: go test ./...
      - name: Build
        run: make
  test-python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools build wheel twine
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build the package
        run: |
          python3 -m build --sdist
